name: Builds, tests & co

on:
  push:
    branches:
      - main
  pull_request:

env:
  OPAMCRITERIA: +removed,+count[version-lag,solution]
  OPAMFIXUPCRITERIA: +removed,+count[version-lag,solution]
  OPAMUPGRADECRITERIA: +removed,+count[version-lag,solution]

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 5.3.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Update base system
        run: sudo apt update

      - name: Install system requirements
        run: sudo apt install -y libsdl2-dev

      - name: Install ocaml requirements
        run: opam install . --deps-only --with-test --with-dev-setup --with-doc

      - name: Build check
        run: opam exec -- dune build

      - name: Run tests
        run: opam exec -- dune runtest

      - name: Check formatting
        run: opam exec -- dune build @fmt

      - name: Build docs
        run: opam exec -- dune build @doc
